model: yolov5m-cls.pt
data: D:/PyCharm/SmartJianKong/yolov5_master/datasets/my_datas
epochs: 54
batch_size: 16
imgsz: 224
nosave: false
cache: null
device: '0'
workers: 8
project: ..\runs\train-cls
name: traffic_exp1
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.0005
lrf: 0.1
decay: 0.0001
label_smoothing: 0.01
cutoff: null
dropout: 0.0
verbose: false
seed: 0
local_rank: -1
save_dir: ..\runs\train-cls\traffic_exp1144
